### ISSUE TITLE
Command to start a kubernetes job

### ISSUE THREAD

**Issue by Akarys42** [python-discord/king-arthur#3]
### Command Name

arthur job start $name

### What should the command do?

This would create and start a new job. Our only use case so far would be to launch a Blackbox backup, although we may have more jobs in the future.

### APIs

- [ ] Cloudflare
- [X] Kubernetes
- [ ] Discord
- [ ] Other

### Who should be authorised to use this command?

DevOps

**Comment by doublevcodes** [comment]
Can I do this :)

**Comment by jb3** [comment]
Added in #7.
